### ISSUE TITLE
Add RNG function callback argument for repeatable random sequences

### ISSUE THREAD

**Issue by MikeLorenz** [8bitskull/dicebag#1]
For instance, if I were creating a puzzle game or a roguelike where each level is randomly generated, it would be useful to be able to be able to store the random seed and know that the same seed will always generate the same level. I imagine this as a parallel set of functions exactly like the current ones, adding an extra parameter for the RNG callback function.

**Comment by 8bitskull** [comment]
Thanks for the suggestion.

I haven't implemented something like this before so not sure how it would look.

Rewriting dicebag.set_up_rng() would be trivial - I could add an optional parameter 'seed' that would replace the socket.gettime() portion, and add a function return for the seed used (either the parameter or the one generated by socket.gettime()). This way you could choose to recreate a particular seed.

When you say "a parallel set of functions" you've lost me! How would that work?

**Comment by MikeLorenz** [comment]
What I meant by a parallel set of functions is: a separate set of functions just like the current set, but named slightly differently, like flip_coin_x(), roll_dice_x(), etc. But I don't think that's necessary.

Your idea of passing a seed parameter is a good step. Maybe that's all you need, but something a little more flexible would be to also allow passing an RNG function to set_up_rng() that replaces math.random. I don't know what math.random's algorithm is, but often the standard RNG algorithm is crap, so I always like the option to use my own.

**Comment by 8bitskull** [comment]
Alright, for now I will make the proposed changes to set_up_rng() because I think there's a good case for them. math.randomseed() of course already takes a seed as a parameter, so the only additional benefit the dicebag function has is that a) it creates a nice random (based on socket.gettime) seed by default, and b) it clears the 'bad' first few rolls. I don't know how or why the first few rolls are less random than others, it just seems to be commonly accepted to be the case.

In terms of replacing math.random with a custom function, that is easily done and does not require a dicebag function. For example, I think this would work (for a very bad custom random function):
```

print(math.random())

local function always_42()
    return 42
end

math.random = always_42

print(math.random())
```

Example output:
0.84018771715471
42

**Comment by MikeLorenz** [comment]
Looks good, thanks!

**Comment by 8bitskull** [comment]
Added in 0.2.
